# docker‑compose.yml  ── local dev & staging
#version: "3.9"

services:
  # ──────────────────────────────── MariaDB ────────────────────────────────
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: wp
    volumes:
      - db_data:/var/lib/mysql

  # ─────────────────────────────── WordPress ───────────────────────────────
  wordpress:
    build: ./wordpress              # custom Dockerfile (GraphQL plugin baked in)
    restart: unless-stopped
    expose:
      - "80"                        # Traefik picks it up via labels
    environment:
      DB_NAME:     wp
      DB_USER:     root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      DB_HOST:     db
      WP_ENV:      ${WP_ENV:-development}
      # Public URLs shown to WordPress
      WP_HOME:     ${WP_HOME:-http://localhost:8080}
      WP_SITEURL:  ${WP_SITEURL:-http://localhost:8080/wp}
    volumes:
      - uploads:/var/www/html/web/app/uploads
    labels:
      # ─ Traefik – production FQDNs
      - traefik.enable=true
      - traefik.http.routers.wp.rule=Host(`wp.robertfisher.com`)
      - traefik.http.routers.wp.entrypoints=websecure
      - traefik.http.routers.wp.tls.certresolver=cf
      - traefik.http.services.wp.loadbalancer.server.port=80
      # ─ Traefik – local shortcuts
      - traefik.http.routers.wp-local.rule=Host(`localhost`) && ( PathPrefix(`/wp`) || PathPrefix(`/graphql`) || Path(`/favicon.ico`) )
      - traefik.http.routers.wp-local.entrypoints=web
      - traefik.http.routers.wp-local.priority=12
    depends_on:
      - db

  # ──────────────────────────────── Next.js ────────────────────────────────
  next:
    # Build the image from the mono‑repo package folder
    build:
      context: ./nextjs-site
      args:
        # ⬅ Inject GraphQL URL during `docker build`
        NEXT_PUBLIC_WPGRAPHQL_URL: http://wordpress/graphql
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      # ⬅ Same var at *runtime* so fetch() works inside the container
      NEXT_PUBLIC_WPGRAPHQL_URL: http://wordpress/graphql
    labels:
      # ─ Traefik – production FQDNs
      - traefik.enable=true
      - traefik.http.routers.next.rule=Host(`robertfisher.com`) || Host(`www.robertfisher.com`)
      - traefik.http.routers.next.entrypoints=websecure
      - traefik.http.routers.next.tls.certresolver=cf
      - traefik.http.services.next.loadbalancer.server.port=3000
      # ─ Traefik – local shortcut
      - traefik.http.routers.next-local.rule=Host(`localhost`)
      - traefik.http.routers.next-local.entrypoints=web
      - traefik.http.routers.next-local.priority=10
      - traefik.http.services.next.loadbalancer.server.port=3000
    depends_on:
      - wordpress

  # ──────────────────────────────── Traefik ────────────────────────────────
  traefik:
    image: traefik:3
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.cf.acme.dnschallenge=true"
      - "--certificatesresolvers.cf.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cf.acme.email=${LE_EMAIL:-local@example.com}"
      - "--certificatesresolvers.cf.acme.storage=/letsencrypt/acme.json"
    environment:
      CLOUDFLARE_DNS_API_TOKEN: ${CLOUDFLARE_DNS_API_TOKEN:-dev}
      LE_EMAIL: ${LE_EMAIL:-local@example.com}
    ports:
      - "80:80"      # HTTP   → local Traefik dashboard / wp-local / next-local
      - "8080:80"    # Map extra host‑port for WP local dev
      - "443:443"    # HTTPS  (prod)
      - "8443:443"   # HTTPS  (optional extra)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - le:/letsencrypt

# ──────────────────────────────── Volumes ────────────────────────────────
volumes:
  db_data:
  uploads:
  le:
