# docker‑compose.yml  ── local dev & staging
#version: "3.9"

services:
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: wp
    volumes:
      - db_data:/var/lib/mysql

    # ----- OFFICIAL HEALTH‑CHECK ---------------------------------
    # Uses the script bundled in mariadb:11 images. It waits for
    # the TCP socket to accept connections *and* for InnoDB to be
    # fully initialised before reporting “healthy”.
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 6

  wordpress:
    build: ./wordpress
    restart: unless-stopped
    expose: [ "80" ]
    environment:
      DB_NAME:       wp
      DB_USER:       root
      DB_PASSWORD:   ${MYSQL_ROOT_PASSWORD:-secret}
      DB_HOST:       db
      WP_ENV:        ${WP_ENV:-development}
      WP_HOME:       ${WP_HOME:-http://localhost:8080}
      WP_SITEURL:    ${WP_SITEURL:-http://localhost:8080/wp}
    volumes:
      - uploads:/var/www/html/web/app/uploads
    labels:
      - traefik.enable=true
      - traefik.http.routers.wp.rule=Host(`wp.${DOMAIN:-example.com}`)
      - traefik.http.routers.wp.entrypoints=websecure
      - traefik.http.routers.wp.tls.certresolver=cf
      - traefik.http.services.wp.loadbalancer.server.port=80
      - traefik.http.routers.wp-local.rule=Host(`localhost`) && ( PathPrefix(`/wp`) || PathPrefix(`/graphql`) || Path(`/favicon.ico`) )
      - traefik.http.routers.wp-local.entrypoints=web
      - traefik.http.routers.wp-local.priority=12
    depends_on:
      db:
        condition: service_healthy

  next:
    build:
      context: ./nextjs-site
      args:
        NEXT_PUBLIC_WPGRAPHQL_URL: http://wordpress/graphql
    restart: unless-stopped
    expose: [ "3000" ]
    ports:  [ "3000:3000" ]
    environment:
      NEXT_PUBLIC_WPGRAPHQL_URL: http://wordpress/graphql
    labels:
      - traefik.enable=true
      - traefik.http.routers.next.rule=Host(`${DOMAIN:-example.com}`) || Host(`www.${DOMAIN:-example.com}`)
      - traefik.http.routers.next.entrypoints=websecure
      - traefik.http.routers.next.tls.certresolver=cf
      - traefik.http.services.next.loadbalancer.server.port=3000
      - traefik.http.routers.next-local.rule=Host(`localhost`)
      - traefik.http.routers.next-local.entrypoints=web
      - traefik.http.routers.next-local.priority=10
    depends_on:
      wordpress:
        condition: service_started

  traefik:
    image: traefik:3
    restart: unless-stopped
    command:
      - --log.level=INFO
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # ACME → Cloudflare DNS‑01
      - --certificatesresolvers.cf.acme.dnschallenge=true
      - --certificatesresolvers.cf.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cf.acme.email=${LE_EMAIL:-local@example.com}
      - --certificatesresolvers.cf.acme.storage=/letsencrypt/acme.json
      # Request apex *and* wildcard certs on container start
      - --certificatesresolvers.cf.acme.domains=${DOMAIN:-example.com},*.${DOMAIN:-example.com}
    environment:
      CLOUDFLARE_DNS_API_TOKEN: ${CLOUDFLARE_DNS_API_TOKEN:-dev}
      LE_EMAIL: ${LE_EMAIL:-local@example.com}
    ports:
      - "80:80"
      - "8080:80"
      - "443:443"
      - "8443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - le:/letsencrypt

volumes:
  db_data:
  uploads:
  le:
