import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

/**
 * The `.woff2` files must live under
 *   nextjs-site/public/fonts/
 * so they are served at  /fonts/…  by Next.js.
 */
const geistSans = localFont({
  src: "../public/fonts/geist-sans.woff2",
  variable: "--font-geist-sans",
  display: "swap",
});

const geistMono = localFont({
  src: "../public/fonts/geist-mono.woff2",
  variable: "--font-geist-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
